### ISSUE TITLE
Bridgefy.manager.stop() Does Not Exist

### ISSUE THREAD

**Issue by christianrolph** [bridgefy/sdk-ios-beta#14]
**Describe the bug**
There is no function associated with Bridgefy.manager.stop()
When you enter this line of code into Xcode, the compiler throws an error that "Value of type 'Bridgefy' has no member 'stop'.

**To Reproduce**
1. Insert line of code Bridgefy.manager.stop() into Xcode
2. See error message "Value of type 'Bridgefy' has no member 'stop'.

**Expected behavior**
Function should exist and not throw any compiler errors.

**Screenshots**
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/55676161/215294519-1ee6582e-a793-4340-a487-83ed2a123a2c.png">

**Smartphone (please complete the following information):**
 - Xcode: 14.2

**Additional context**

**Comment by ghbfy** [comment]
Hi @christianrolph
This issue is fixed on version 0.3.0
