### ISSUE TITLE
No response

### ISSUE THREAD

**Issue by enTong2017** [bridgefy/sdk-ios-beta#20]
![image](https://user-images.githubusercontent.com/110648709/231971006-6b4e536f-a6f5-4638-bd0a-c0262a289d65.png)
I Initialize the SDK(ver 0.3.0) like the doc said, but it has no response or any error log with the BridgefySDK.

**Comment by ghbfy** [comment]
Hi @enTong2017!
Please update the SDK to the latest version and let me know if you're still having problems.

**Comment by enTong2017** [comment]
> Hi @enTong2017!
> Please update the SDK to the latest version and let me know if you're still having problems.

**Comment by enTong2017** [comment]
Hi, @ghbfy !
I had updated the latest version, but it still has this problem.
