### ISSUE TITLE
TransmissionMode

### ISSUE THREAD

**Issue by enTong2017** [bridgefy/sdk-ios-beta#6]
The transmissionMode of current BridgefySDK only has p2p mode? 
What time can I use the broadcast mode?

**Comment by ghbfy** [comment]
Hi! We are working on it, as soon as we release a new version with this feature we'll let you know.

**Comment by enTong2017** [comment]
> Hi! We are working on it, as soon as we release a new version with this feature we'll let you know.

any target date for this new release?

**Comment by AmnaNaved** [comment]
Hi, We are using Bridgefy in our iOS app. The latest SDK beta version supports only P2P mode, any updates when we can expect to have Broadcast chat.

**Comment by ghbfy** [comment]
Hi @enTong2017 
Version 0.3.0 has all three transmission modes working
